FROM centos:7

RUN yum install epel-release python2-devel python2-pip gcc gcc-c++ glib-devel glibc-devel tigervnc-server git -y && pip install --upgrade pip && pip install --ignore-installed kubernetes xmljson xmltodict watchdog pyyaml pyinstaller grpcio grpcio-tools protobuf psutil





